### ISSUE TITLE
error executing

### ISSUE THREAD

**Issue by gurkburk76** [rdvm/zfs-status-to-discord#1]
Granted i'm a bit of an idiot when it comes to python, but perhaps there is a problem with slighty newer versions?

root@pve:~/zfs-status-to-discord# python3 main.py
Traceback (most recent call last):
  File "/root/zfs-status-to-discord/main.py", line 137, in <module>
    main()
  File "/root/zfs-status-to-discord/main.py", line 134, in main
    zfs_report()
  File "/root/zfs-status-to-discord/main.py", line 81, in zfs_report
    state_msg = get_state()
                ^^^^^^^^^^^
  File "/root/zfs-status-to-discord/main.py", line 46, in get_state
    section = get_section("state:", "status:")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/zfs-status-to-discord/main.py", line 33, in get_section
    ind_end = words.index(end)
              ^^^^^^^^^^^^^^^^
ValueError: 'status:' is not in list

python version: 
root@pve:~/zfs-status-to-discord# python3 -V
Python 3.11.2

**Comment by rdvm** [comment]
It looks like it's not finding `status:` in the output. Could you share the output of just manually running `/sbin/zpool status` ?
